knp_snappy:
    pdf:
        enabled:    true
        binary:     '"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe"'
        options:    
            enable-local-file-access: true
            disable-smart-shrinking: false
    image:
        enabled:    true
        binary:     '"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltoimage.exe"'
        options:    []
