parameters:
    app.openweathermap.api_key: '%env(OPENWEATHERMAP_API_KEY)%'

services:
    App\WeatherBundle\Service\WeatherService:
        arguments:
            $httpClient: '@http_client'
            $apiKey: '%app.openweathermap.api_key%'
